query User (
    $id: [QueryArgument]
    $email: [String]
) {
    user (
        id: $id
        email: $email
    ) {
        id
        email
        firstName
        lastName
        fullName
        addresses {
            ... on Address {
                id
                title
                firstName
                lastName
                fullName
                organization
                addressLine1
                addressLine2
                locality
                administrativeArea
                countryCode
                postalCode
                phone
            }
        }
    }
}
